### ISSUE TITLE
Hand Rolled Crypto

### ISSUE THREAD

**Issue by Term1nal** [IOT-DSA/sdk-dslink-dart#10]
After having taken a cursory look at the project codebase, I have found one very alarming fact. The crypto seems to be some sort of augmented, hand-rolled diffie-hellman. I'm not a cryptography expert, but one thing that I have learned over the years by following the infosec community, is that crypto people are a lot smarter than I am. They pull apart the implementation details with a fine toothed comb and find every little unforeseen weakness that you or I could never have imagined.

For this reason, I have learned that doing one's own cryptography implementation is typically a horrendously bad idea. With the aim of the IOT-DSA to be a ubiquitous standard for a whole host of little devices. Devices that may rarely if ever have firmware updates once they're in the wild, deployed, and forgotten about until they break... if this sort of design choice is made from the get go without proper vetting, research, verification, and testing... it will come back to haunt.

I suggest that the crypto implementation in IOT-DSA be replaced with an equivalent purpose-built library. One such that I have found for Dart (a hard task to be sure), is mostly a clone of BouncyCastle (widely used with many different language implementations). It contains tests and verification of standards compliance.

https://pub.dartlang.org/packages/cipher

Perhaps using an ECDSA key exchange (far less processing power required due to lower key lengths required as compared to factorization to get the same cryptographic strength, just what the doctor ordered with regard to small embedded devices with low-power processors.) for the session key and salt using this library would be far more of a smart design decision than trying to do the math ourselves.

**Comment by rinick** [comment]
Hi, 
actually the output of the current encryption algorithm is same as the cipher result as dart cipher lib
the cipher lib use block based encryption. in dslink hand shake, the encryption of nonce bytes never need more than 1 block, so all the complexity in block encryption are not necessary here. implementing it directly with bignum instead of using any cipher library makes the code much easier to port and test.

At first I didn't worry about performance of DSA part since it's only needed at handshake, not in every message. but now the time it takes to generate a private-public key pair is actually becoming a problem, since EC based key pair should be faster to generate, maybe we should use ECDSA

**Comment by Term1nal** [comment]
Yeah, I would definitely suggest ECDSA, Longer key length difficulty with ECDSA doesn't become a logarithmic performance problem like factorization does (RSA), but signature verification is not as fast. There's a tradeoff in generation time due to a fewer number of bits required and the signature verification, but in the long run the net result is still significantly faster than factorization style key exchange as the latter grows into the 4069bit and eventually 8192bit key lengths.

Use of a lib would be preferable. While I understand the design decision for portability and cleanliness, I don't think for the sake of security that relying on a hand-made implementation is a sane thing to do.

For Dart, we have cipher, and for java we have BouncyCastle (what cipher is based off of more or less). With JavaScript.. I can imagine with the popularity of it there's also a reliable implementation but I haven't researched that yet. Go (if I or anyone else ever get around to porting a Go version of the SDK) has most of this built into the standard library.
