### ISSUE TITLE
MaxRollup and MinRollup don't work

### ISSUE THREAD

**Issue by ajsergeev** [IOT-DSA/sdk-dslink-dart#48]
Simple test fails:
  test("test get_history", () {
    MaxRollup rlp = new MaxRollup();
    rlp.add(43);
    rlp.add("101");
    expect(rlp.value, equals(101));
    MinRollup mrlp = new MinRollup();
    mrlp.add(43);
    mrlp.add("101");
    expect(mrlp.value, equals(43));
  });

**Comment by Pacane** [comment]
@ajsergeev is that fixed now?

**Comment by ajsergeev** [comment]
I think yes, you can close this
